import {
  CIRCULAR_HIERARCHY_PREVIEW_WIDTH,
  MATRIX_HIERARCHY_PREVIEW_WIDTH,
} from "@/config/ui";

export const CIRCULAR_PREVIEW_WIDTH = CIRCULAR_HIERARCHY_PREVIEW_WIDTH;
export const MATRIX_PREVIEW_WIDTH = MATRIX_HIERARCHY_PREVIEW_WIDTH;
